### ISSUE TITLE
Crash when computing proxy:

### ISSUE THREAD

**Issue by avclubvids** [graphdeco-inria/nerfshop#2]
The proxy cage generation crashes when trying to select floaters. There is a long pause as it processes, then the program exits without an error. Here are the only logs in the terminal when it happens:

```
Reprojected 176 rays
17:52:48 INFO     #vertices=4111 #triangles=8138
```

This is on a pretty small dataset (15 images) running on an RTX8000 using nerfshop-RTX-2000.exe. I have been able to correctly generate a proxy and manipulate a smaller more resolved object so this might be something to do with the more amorphous nature of the floaters?

**Comment by clementjambon** [comment]
Hello @avclubvids 
Thank you very much for your feedback! It turns out that we have identified the issue and I am currently working on a fix. I'll keep you posted :wink:

**Comment by clementjambon** [comment]
This should now be fixed.

**Comment by clementjambon** [comment]
I just updated the binaries too.

**Comment by avclubvids** [comment]
This is still a problem, using the updated binaries from yesterday:

```
12:40:29 INFO     #vertices=2225 #triangles=4406
12:42:46 ERROR    Uncaught exception: bad allocation
```

**Comment by clementjambon** [comment]
I have made an extra fix and updated the binaries. Could you tell me if you are still able to reproduce the bug?

**Comment by avclubvids** [comment]
The new binaries from yesterday work! I was still able to crash it, but I think that was me doing too much in the viewport while it was trying to process it. I have a feature suggestion I'll put in a new issue, you can take or leave that one but I think you have an easy win within reach :)
